
<style>
	
	#chartContainer, #chartContainer2 {
		margin-left: auto;
    margin-right: auto;
	}

</style>


<!-- <div class="panel panel-success">
  <div class="panel-heading">Gráfico dos projetos</div>
  <div class="panel-body">
    <form class="form-inline" action="#">
	  <div class="form-group">
	    <input type="text" class="form-control" id="date_de" placeholder="de">
	  </div>
	  <div class="form-group">
	    <input type="email" class="form-control" id="date_ate" placeholder="até">
	  </div>
		<button type="submit" class="btn btn-default">Procurar</button>
		<button type="submit" class="btn btn-default">Limpar filtros</button>
	</form>
  </div>
</div>

<div id="chartContainer" style="height: 300px; width: 833px; margin-bottom:35px;">
</div> -->


<div class="panel panel-success">
  <div class="panel-heading">Gráfico dos funcionários</div>
  <div class="panel-body">
    <form class="form-inline" action="<?php echo $this->baseUrl("admin"); ?>" method="POST">
	  <div class="form-group">
	    <input type="text" class="form-control" id="date_de2" name="de"  placeholder="<?php if(isset($this->i1)) {echo date('d/m/Y', $this->i1);}else {echo 'de';} ?>">
	  </div>
	  <div class="form-group">
	    <input type="text" class="form-control" id="date_ate2" name="ate" placeholder="<?php if(isset($this->i2)) {echo date('d/m/Y', $this->i2);}else{echo 'até';}   ?>">
	  </div>
		<button type="submit" class="btn btn-default">Procurar</button>
		<button type="submit" class="btn btn-default" name="limpar">Limpar filtros</button>
	</form>
  </div>
</div>
<div id="chartContainer2" style="height: 300px; width: 833px;">
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



<script type="text/javascript">
$(document).ready(function () {
    /* assuming that text input datePicker would have id='datePicker' */
    $( "#date_de" ).datepicker({ dateFormat: 'dd/mm/yy' });
    $( "#date_ate" ).datepicker({ dateFormat: 'dd/mm/yy' });
    $( "#date_de2" ).datepicker({ dateFormat: 'dd/mm/yy' });
    $( "#date_ate2" ).datepicker({ dateFormat: 'dd/mm/yy' });
});
window.onload = function () {
		var chart = new CanvasJS.Chart("chartContainer2", {
			title:{
				text:"Etapas relizadas"
			},
                        animationEnabled: true,
			axisX:{
				interval: 1,
				gridThickness: 0,
				labelFontSize: 11,
				labelFontStyle: "normal",
				labelFontWeight: "normal",
				labelFontFamily: "Lucida Sans Unicode"

			},
			axisY2:{
				interlacedColor: "rgba(1,71,101,.2)",
				gridColor: "rgba(1,71,101,.1)"

			},

			data: [
			{     
				type: "bar",
                name: "companies",
				axisYType: "secondary",
				color: "#014D65",				
				dataPoints: [
				
				<?php 

				foreach ($this->resultado as $key => $value) {
					echo '{y: '.$value['qtd'].', label: "'.$value['nome'].'"  },';
				}

				 ?>
				]
			}
			
			]
		});

chart.render();



var chart = new CanvasJS.Chart("chartContainer",
    {
      title:{
        text: "Projetos"    
      },
      animationEnabled: true,
      axisY: {
        title: "quantidade projetos"
      },
      legend: {
        verticalAlign: "bottom",
        horizontalAlign: "center"
      },
      theme: "theme2",
      data: [

      {        
        type: "column",  
        showInLegend: true, 
        legendMarkerColor: "grey",
        legendText: "Projetos realizados nos últimos meses",
        dataPoints: [      
        {y: 33, label: "Ago/2014"},
        {y: 45,  label: "Set/2014" },
        {y: 55,  label: "Out/2014"},
        {y: 101,  label: "Nov/2014"},
        {y: 10,  label: "Dez/2014"},
        {y: 50, label: "Jan/2015"},
        {y: 33,  label: "Fev/2015"},        
        {y: 90,  label: "Mar/2015"},
        {y: 144,  label: "Abr/2015"}        
        ]
      }   
      ]
    });

   // chart.render();

}


  </script>


