<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
       	<?php //echo $this->headTitle(); ?>
		<title>Administração de conteúdo</title>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<link rel="stylesheet" href="<?php echo $this->baseUrl("/js/jquery-ui-1.11.3/jquery-ui.css"); ?>">

    <script src="<?php echo $this->baseUrl("/js/jquery-ui-1.11.3/jquery-ui.min.js"); ?>"></script>

		<script type="text/javascript" src="<?php echo $this->baseUrl("js/nicEdit.js"); ?>"></script>


        <link href="<?php echo $this->baseUrl("bootstrap/dist/css/bootstrap.min.css"); ?>" rel="stylesheet">

        <script src="<?php echo $this->baseUrl("bootstrap/dist/js/bootstrap.min.js"); ?>"></script>
        
        <script src="<?php echo $this->baseUrl("/js/canvas.js"); ?>"></script>
    
    <style>
    .errors {
      color: red;
      padding: 0;
      list-style: none;
    }
    </style>

    </head>
    <body>
        <?php $controllerValue =  Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>
        <section class="container">

            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="#">Gerenciador de projetos</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <?php if( $this->authStatus ): ?>
                  <ul class="nav navbar-nav">
                    <li <?php if($controllerValue == 'index') echo'class="active"';  ?> ><a href="<?php echo $this->baseUrl('/admin'); ?>">Inicial<span class="sr-only">(current)</span></a></li>
                    <li <?php if($controllerValue == 'projetos') echo'class="active"';  ?>><a href="<?php echo $this->baseUrl('/admin/projetos'); ?>">Projetos</a></li>
                    
                    <!-- Funcionários -->
                    <li  <?php if($controllerValue == 'funcionarios') {echo'class="dropdown active"';}else{echo'class="dropdown"'; }  ?>  >
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Funcionários<span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo $this->baseUrl('/admin/funcionarios/cadastrar'); ?>">Cadastrar</a></li>
                        <li><a href="<?php echo $this->baseUrl('/admin/funcionarios/visualizar'); ?>">Visualizar</a></li>
                        
                      </ul>
                    </li>
                    

                    <!-- Clientes -->
                    <li  <?php if($controllerValue == 'clientes') {echo'class="dropdown active"';}else{echo'class="dropdown"'; }  ?>  >
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Clientes<span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo $this->baseUrl('/admin/clientes/cadastrar'); ?>">Cadastrar</a></li>
                        <li><a href="<?php echo $this->baseUrl('/admin/clientes/visualizar'); ?>">Visualizar</a></li>
                        <li><a href="<?php echo $this->baseUrl('/admin/projetos/adicionar'); ?>">Projetos</a></li>
                      </ul>
                    </li>


                    <li  <?php if($controllerValue == 'adminc') {echo'class="dropdown active"';}else{echo'class="dropdown"'; }  ?>  >
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin(s)<span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo $this->baseUrl('/admin/adminc/cadastrar'); ?>">Cadastrar</a></li>
                        <li><a href="<?php echo $this->baseUrl('/admin/adminc/visualizar'); ?>">Visualizar</a></li>
                      </ul>
                    </li>

                    <li <?php if($controllerValue == 'relatorios') {echo'class="dropdown active"';} else { echo'class="dropdown"'; }   ?> >

                      <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" href="<?php echo $this->baseUrl('/admin/relatorios'); ?>">Relatórios<span class="caret">
                          <span class="sr-only">(current)</span></a>

                      <ul class="dropdown-menu" role="menu">
                        <li>
                          <a href="<?php echo $this->baseUrl('admin/relatorios/tgnp'); ?>">Tempo gasto nos projetos</a>
                        </li>
                        <li>
                          <a href="<?php echo $this->baseUrl('/admin/adminc/visualizar'); ?>">Projetos realizados</a>
                        </li>
                        <li>
                          <a href="<?php echo $this->baseUrl('/admin/adminc/visualizar'); ?>">Etapas realizadas pelos funcionários</a>
                        </li>
                        
                      </ul>
                    </li>

                  </ul>
                  

                  <ul class="nav navbar-nav navbar-right ">
                    <li><a href="<?php echo $this->baseUrl('/admin/auth/logout'); ?>">Sair</a></li>
                  </ul>


                  <?php endif; ?>
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
            </nav>

            <section id="content" class="row">
                <section class="span12">
                    <?php echo $this->Layout()->content; ?>
                </section>
            </section>
            
            <!--
            <div id="dialog" title="Excluir">
              <p>Deseja mesmo excluir o funcionário?</p>
            </div> -->



        </section>

        <script type="text/javascript">
            var BASEURL = "<?php echo $this->baseUrl("/"); ?>";
        </script>
		<script type="text/javascript">
			//bkLib.onDomLoaded(function() { new nicEditor({fullPanel : true}).panelInstance('conteudo'); });

              $(function() {
    
    $( "#dialog" ).dialog({
      resizable: false,
      height:161,
      modal: true,
      buttons: {
        "OK": function() {
          $( this ).dialog( "close" );
        },
        Cancelar: function() {
          $( this ).dialog( "close" );
        }
      }
    });


  });


      $( document ).ready(function() {



      });

		</script>


    </body>
</html>
