<ol class="breadcrumb">
  <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Clientes</li>
  <li class="active"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>  Visualizar</li>
</ol>



<p>
<a href="<?php echo $this->baseUrl("admin/clientes/cadastrar"); ?>">
<button type="button" class="btn btn-default">Adicionar</button>
</a>
</p>


<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Procurar Clientes...">
      <span class="input-group-btn">
        <button class="btn btn-success" type="button">Buscar</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->


<?php if (count($this->messages)) : ?>
    <br>
    <?php foreach ($this->messages as $message) : ?>
       <?php echo $message; ?>
    <?php endforeach; ?>
<?php endif; ?>

<br>

<table class="table table-hover">

<tr>
	<td><strong>Nome</strong></td>
	<td><strong>Data registro</strong></td>
	<td></td>
</tr>

<?php
 foreach ($this->registros as $clientes):
?>
	<tr>
		<td> <?php echo $clientes['nome']; ?> </td>
		<td><?php echo date( 'd/m/Y',strtotime($clientes['data'])); ?></td>
		<td> <a href="<?php echo $this->baseUrl("admin/clientes/editar/id/" . $clientes['id']); ?>"><button class="btn btn-info btn-xs">  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar</button> </a>
		
    <a href="<?php echo $this->baseUrl("admin/clientes/delete/id/" . $clientes['id']); ?>" onclick="return confirm('Você quer excluir esse cliente?')">
    <button class="btn btn-danger btn-xs">  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Excluir</button></a>
		</td>
	</tr>

<?php
 endforeach;
 ?>

</table>



<?php
    echo $this->paginationControl(
                $this->registros,
                'Sliding',
                'paginator.phtml'
            );

?>