<ol class="breadcrumb">
  <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Clientes</li>
  <li class="active"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>  Visualizar</li>
</ol>



<p>
<a href="<?php echo $this->baseUrl("admin/clientes/cadastrar"); ?>">
<button type="button" class="btn btn-default">Adicionar</button>
</a>
</p>


<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control find" placeholder="Procurar Clientes...">
      <span class="input-group-btn">
        <button class="btn btn-success" type="button" onclick="buscar_clientes()">Buscar</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->


<?php if (count($this->messages)) : ?>
    <br>
    <?php foreach ($this->messages as $message) : ?>
       <?php echo $message; ?>
    <?php endforeach; ?>
<?php endif; ?>

<br>

<!-- Adaptação1 - Início -->
<style>
  .selecionados {
    background-color:#F5F5F5 ;
    border: 1px dotted #c2c2c2;
    border-radius: 10px;
    padding:10px;
  }

  .resultado {
    color: #ff0000;
    padding:10px;
  }
</style>
<div class="selecionados">
  <b>Selecionados</b> 
  <button onclick="selecionarTodos(this)">Todos</button>
  <button onclick="procura_usuarios()">Excluir</button>
</div>


<!-- Adaptação1 - Fim -->

<table class="table table-hover" id="tabela_usuarios">
  <tr>
    <td></td>
  	<td><strong>Nome</strong></td>
  	<td><strong>Data registro</strong></td>
  	<td></td>
  </tr>
<?php
 foreach ($this->registros as $clientes):
?>
	<tr class="ck_user<?php echo $clientes['id'] ?>">
    <td > <input class="checkbox<?php echo $clientes['id'] ?>" type="checkbox" name="vehicle" value="<?php echo $clientes['id'] ?>" > </td>
		<td> <?php echo $clientes['nome']; ?> </td>
		<td><?php echo date( 'd/m/Y',strtotime($clientes['data'])); ?></td>
		<td> <a href="<?php echo $this->baseUrl("admin/clientes/editar/id/" . $clientes['id']); ?>"><button class="btn btn-info btn-xs">  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar</button> </a>
		
    <a href="<?php echo $this->baseUrl("admin/clientes/delete/id/" . $clientes['id']); ?>" onclick="return confirm('Você quer excluir esse cliente?')">
    <button class="btn btn-danger btn-xs">  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Excluir</button></a>
		</td>
	</tr>

<?php
 endforeach;
 ?>

</table>

<script type="text/javascript">

  function buscar_clientes() {
    var input;
    input = document.getElementsByClassName("find")[0].value.trim();
    if(input.length != 0) {
      window.location.replace(BASEURL + "admin/clientes/visualizar/procurar/" + input);
    } else {
      window.location.replace(BASEURL + "admin/clientes/visualizar");
    }
  }


  var tabelaUser = "tabela_usuarios";

  //marca todos os checkbox dos usuários
  function selecionarTodos(obj) {
    var valor;

    container = document.getElementById(tabelaUser);
    items = container.getElementsByTagName('input');
    label = obj.innerHTML; // Valor presente no botão. Poder ser todos, ou nenhum
    if (label == "Todos") {
      obj.innerHTML = "Nenhum";
      valor = true;
    } else {
      obj.innerHTML = "Todos";
      valor = false;
    }

    for (var j = 0; j < items.length; j++) {
        //Se o elemento está visível na página
        if(  $(items[j]).is(":visible") == true )
        {  
             items[j].checked = valor;
        }

    }

  }

  //Procura usuários que estão selecionados, para cumprir com
  //uma determinada ação
  function procura_usuarios() {
    if (!confirm('Deseja realmente excluir os clientes?')) {
        return false;
    }

    var anchor = null;
    var container;
    var items;
    var resultado;
    resultado = '';

    container = document.getElementById(tabelaUser);
    items = container.getElementsByTagName('input');

    for (var j = 0; j < items.length; j++) {
        if(items[j].checked == true) {
          idCliente = items[j].value; // return string
          $.ajax({
            type: 'POST',
            url: BASEURL + 'admin/clientes/ajaxexcluir', //Adaptação1 <= Especificar a url
            data: { id : idCliente },
            async: false,
            success: function(response) {
              resultado = resultado + response;
            }

          });

          //Verifica se a classe 'resultado' existe
          if (!$(".resultado")[0]){
              $(".selecionados").after("<div class='resultado'></div>")
          }

          $('.resultado').html(resultado);
          $(".ck_user" + idCliente).hide();
          $(".checkbox" + idCliente).prop("checked", false);
        }
    }
    return false
  };
</script>



<?php
    echo $this->paginationControl(
                $this->registros,
                'Sliding',
                'paginator.phtml'
            );

?>