<ol class="breadcrumb">
  <li  class="active"><span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span> Projetos</li>
  <li><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>  Adicionar</li>
</ol>

<a href="<?php echo $this->baseUrl('/admin/projetos'); ?>"><button type="button" class="btn btn-success btn-xs"> <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span> Voltar</button></a>

<script>
	$(document).ready(function () {
	    /* assuming that text input datePicker would have id='datePicker' */
	    $( ".data_inicial" ).datepicker({ dateFormat: 'dd/mm/yy' });
	    $( ".data_final" ).datepicker({ dateFormat: 'dd/mm/yy' });
	    $( "#date_de" ).datepicker({ dateFormat: 'dd/mm/yy' });
	    $( "#date_ate" ).datepicker({ dateFormat: 'dd/mm/yy' });
	    
	});

</script>


<style>
	.filtrosp {
		margin-bottom: 10px;
		float: right;
	}
</style>
<div class="filtrosp">
	<form class="form-inline" method="post" action="<?php echo $this->baseUrl("admin/projetos/add"); ?>">
	  <div class="form-group">
	  	<select class="form-control" name="empresas">
	  	<option value="0" label="Todos os clientes" <?php if($this->valor == 0) {echo 'selected';} ?>>Todos os clientes</option>
		<?php 
		foreach ($this->clientes as $key => $value) {
			?>
			<option value="<?php echo $key ?>" label="<?php echo $value ?>" <?php if($this->valor == $key) {echo 'selected'; } ?>><?php echo $value ?></option>
		  
			<?php
		}
		 ?>

		</select>
	  	
	    <input type="text" class="form-control" name="date_de" id="date_de" placeholder="de" value="<?php echo $this->data_de; ?>">
	  </div>
	  <div class="form-group">
	    <input type="text" class="form-control" name="date_ate" id="date_ate" placeholder="até" value="<?php echo $this->data_ate; ?>">
	  </div>
		<button type="submit" class="btn btn-default">Procurar</button>
		
	</form>
</div>

<div class="listaprojetos">
	<table class="table table-hover">

		<tr>
			<td></td>
			<td>Cod.</td>
			<td><strong>Nome</strong></td>
			<td><strong>Data Inicial</strong></td>
			<td><strong>Data Final</strong></td>
			<td><strong>Dias restantes</strong></td>
		</tr>

		<?php
		 foreach ($this->registros as $projetos):
		$mostrar_conteudo = 1;


		if($this->filtroParam == "concluido"  &&  $this->projetos($projetos['id']) != 100)  {
			$mostrar_conteudo = 0;
		}


		if($this->filtroParam == "andamento"  &&  $this->projetos($projetos['id']) == 100 ) {
			$mostrar_conteudo = 0;
		}


		if($this->filtroParam == 'atrasado' &&  $this->projetos($projetos['id']) == 100){
		 	$mostrar_conteudo = 0;
		}



		if($mostrar_conteudo == 1) {
		?>
			<tr>

				<td> <a href="<?php echo $this->baseUrl("admin/projetos/lancar/id/" . $projetos['id']); ?>"><button class="btn btn-default btn-xs"> Adicionar</button> </a>
				</td>
				<td><?php echo $projetos['codigo_projeto']; ?></td>
				<td>  <a href="<?php echo $this->baseUrl("admin/projetos/etapas/id/" . $projetos['id']); ?>"> <?php echo '<strong>'.$projetos['nome_cliente'] . '</strong> - ' . $projetos['nome']; ?> </a></td>
				<td><?php echo date('d/m/Y',strtotime($projetos['inicio'])); ?></td>
				<td><?php echo date('d/m/Y',strtotime($projetos['fim'])); ?></td>

				<td><?php 
					$data_atual =  strtotime(date("m/d/Y")); 
					$data_projeto_entrega = strtotime(   $projetos['fim']   );
					$data1 = new DateTime( date('Y/m/d',strtotime($projetos['fim'])) );
			        $data2 = new DateTime(  date("Y/m/d")	 );
			        $intervalo = $data1->diff( $data2 );
			        echo $intervalo->d;
			        if(  ($data_atual > $data_projeto_entrega) && ($this->projetos($projetos['id']) < 100)  ) {
						echo ' <span class="label label-danger">Atrasado</span> ';
					}

				 ?></td>
			</tr>

		<?php

		}
		 endforeach;
		 ?>

	</table>

</div>