<ol class="breadcrumb">
  <li  class="active"><span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span> Clientes</li>
  <li><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>  Adicionar</li>
</ol>

<a href="<?php echo $this->baseUrl('admin/grupo/adicionar'); ?>"><button type="button" class="btn btn-success btn-xs"> <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span> Voltar</button></a>

<br>
<style>
	.frm1 {
		width: 300px;
		float: left;
		margin-left: 66px;
	}
	.errors {
		list-style:none;
		color:red;
		padding:0;
	}
</style>
<br>

<p>
	Código: <?php echo $this->dataGrupo['codigo_projeto']; ?>
	</p>
	<p>
	Cliente: <?php echo $this->dadoscliente['0']['nome']; ?>
	
</p>

<div class="frm1">
<?php 
echo $this->frm;
?>
<br>

</div>
<script>
	$(document).ready(function () {
	    /* assuming that text input datePicker would have id='datePicker' */
	    $( ".data_inicial" ).datepicker({ dateFormat: 'dd/mm/yy' });
	    $( ".data_final" ).datepicker({ dateFormat: 'dd/mm/yy' });
	    $( "#date_de" ).datepicker({ dateFormat: 'dd/mm/yy' });
	    $( "#date_ate" ).datepicker({ dateFormat: 'dd/mm/yy' });
	});
</script>


<!-- <style>
	.filtrosp {
		margin-bottom: 10px;
		float: right;
		width: 100%;
		margin-bottom: 20px;
		margin-top: 20px;
	}

	.listaprojetos {
		margin-bottom: 100px;
	}
</style> -->
<!-- <div class="filtrosp">
	<form class="form-inline" method="post" action="<?php echo $this->baseUrl("admin/projetos/adicionar"); ?>">
	  <div class="form-group">
	  	<select class="form-control" name="empresas">
	  	<option value="0" label="Todos os clientes" <?php if($this->valor == 0) {echo 'selected';} ?>>Todos os clientes</option>
		<?php 
		foreach ($this->clientes as $key => $value) {
			?>
			<option value="<?php echo $key ?>" label="<?php echo $value ?>" <?php if($this->valor == $key) {echo 'selected'; } ?>><?php echo $value ?></option>
		  
			<?php
		}
		 ?>

		</select>
	  	<input type="hidden" name="pesquisa" value="pesauiqss">
	    <input type="text" class="form-control" name="date_de" id="date_de" placeholder="de" value="<?php echo $this->data_de; ?>">
	  </div>
	  <div class="form-group">
	    <input type="text" class="form-control" name="date_ate" id="date_ate" placeholder="até" value="<?php echo $this->data_ate; ?>">
	  </div>
		<button type="submit" class="btn btn-default">Procurar</button>
		
	</form>
</div> -->

<div class="listaprojetos">
	<table class="table table-hover">

		<tr>
			<td><strong>Cod</strong></td>
			<td><strong>Nome</strong></td>
			<td><strong>Data Inicial</strong></td>
			<td><strong>Data Final</strong></td>
			<td><strong>%</strong></td>
			<td></td>
			<td><strong>Horas</strong></td>
		</tr>

		<?php
		 foreach ($this->registros as $projetos):
		$mostrar_conteudo = 1;

		if($this->filtroParam == "concluido"  &&  $this->projetos($projetos['id']) != 100)  {
			$mostrar_conteudo = 0;
		}

		if($this->filtroParam == "andamento"  &&  $this->projetos($projetos['id']) == 100 ) {
			$mostrar_conteudo = 0;
		}

		if($this->filtroParam == 'atrasado' &&  $this->projetos($projetos['id']) == 100){
		 	$mostrar_conteudo = 0;
		}

		if($mostrar_conteudo == 1) {
		?>
			<tr>
				<td><?php echo $this->dataGrupo['codigo_projeto']; ?></td>
				<td> <a href="<?php echo $this->baseUrl("admin/projetos/etapas/id/" . $projetos['id'].'/idgrupo/'.$this->grupo_id); ?>"><?php echo $projetos['nome']; ?></a>  </td>
				<td><?php echo date('d/m/Y',strtotime($projetos['inicio'])); ?></td>
				<td><?php echo date('d/m/Y',strtotime($projetos['fim'])); ?></td>

				<td>
					<?php $p =  $this->projetos($projetos['id']); ?>
					<style>
					.progress {
						width: 200px;
					}
					</style>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" aria-valuenow="<?php echo $p; ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $p; ?>%;">
					    <?php echo $p; ?>% completo
					  </div>
					</div>

				 </td>
				 <td>
					 <a href="<?php echo $this->baseUrl("admin/projetos/deletarprojeto/id/" . $projetos['id']  .'/idgrupo/'. $this->grupo_id ); ?>" onclick="return confirm('Você quer excluir esse projeto?')">
	    <button class="btn btn-danger btn-xs">  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Excluir</button></a>
				</td>
				<td>
					<?php echo $this->projetoshoras($projetos['id']) . 'h'; ?>
				</td>
			</tr>

		<?php

		}
		 endforeach;
		 ?>

	</table>

</div>



