<ol class="breadcrumb">
  <li  ><span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span> Projetos</li>
  <li class="active"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>  Etapas</li>
</ol>

<a href="<?php echo $this->baseUrl('admin/projetos/adicionar/idgrupo/'.$this->grupo_id); ?>"><button type="button" class="btn btn-success btn-xs"> <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span> Voltar</button></a>
<br>

<style>
	.frm1 {
		width: 300px;
		float: left;
		margin-left: 66px;
	}
	.etapasp {
		float: left;
		//border: 1px solid #333;
		width: 800px;
		padding: 20px;
	}
</style>

<?php if (count($this->messages)) : ?>
    <br>
    <?php foreach ($this->messages as $message) : ?>
        <?php echo $message; ?>
    <?php endforeach; ?>
<?php endif; ?>

<div class="statusprojeto">
	<br>

	<div class="progress">
	  <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="<?php echo $this->porcentagem; ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $this->porcentagem; ?>%;">
	    <i><?php echo $this->porcentagem . '%'; ?></i>
	  </div>
	</div>

</div>

<style>
	.bg-primary {
		padding:10px;
	}
</style>
<div class="grupo1">
<p class="bg-primary">
	<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
	<strong>Cliente: </strong>
	<?php 
	echo $this->clienteData[0]['nome'];
	?>
	<strong> Código: </strong>
	<?php
	echo $this->clienteData[0]['codigo_projeto'];
	?>
</p>
</div>



<div class="frm1">
	<?php 
		echo $this->frm;
	 ?>
</div>

<script>
	$(document).ready(function () {
	    /* assuming that text input datePicker would have id='datePicker' */
	    $( ".data_inicial" ).datepicker({ dateFormat: 'dd/mm/yy' });
	    $( ".data_final" ).datepicker({ dateFormat: 'dd/mm/yy' });

	});

</script>

<style>
	.etapasp {
		margin-bottom: 333px;
	}
</style>
<div class="etapasp">
	<a href="<?php echo $this->baseUrl('/admin/projetos/addetapas/id/' . $this->idProjeto.'/idgrupo/'.$this->grupo_id); ?>"><button type="button" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-plus" ></span>  Adicionar etapa</button></a></p>
	
	<table class="table table-hover">

		<tr>
			<td></td>
			<td><strong>Nome da etapa</strong></td>
			<td><strong>Nome do funcionário</strong></td>
			<td><strong>Data Inicial</strong></td>
			<td><strong>Data Final</strong></td>
			<td><strong>Status</strong></td> <!-- Concluído (verde) / 
			Em andamento (laranja) / Pendente (vermelho) -->
			<td><strong>Horas</strong></td>
			<td><strong>Km/h</strong></td>
		</tr>
		<?php 

			if($this->etapas[0]['id'] <> NULL) {
				foreach ($this->etapas as $key => $value) {
					$total_h_t = '---';
					$usuario = $this->usuario((int)$value['id_funcionarios']);
					if($usuario) {
						$usuarioName = $usuario[0]['nome'];
					}else {
						$usuarioName = 'sem funcionário';
					}
					# code...
					echo '<tr>';
					echo '<td> <a href="'.$this->baseUrl('admin/projetos/estapasexcluir/id/'.$value['id'].'/idprojeto/'.$this->idProjeto.'/idgrupo/'.$this->grupo_id).'" onclick="return confirm(\'Você quer excluir essa etapa?\')"><span class=" glyphicon glyphicon-trash"></span></a></td>';
					echo '<td><a href="'.$this->baseUrl('admin/projetos/editaretapa/id/' . $value['id'].'/idprojeto/'.$this->idProjeto.'/idgrupo/'.$this->grupo_id).'">'.$value['nome'].'</a></td>';
					echo '<td>'.$usuarioName.'</td>';

					//Procura as datas na qual o projeto foi iniciado
					//e a data na qual o projeto foi finalizado
					$conclusao = $this->conclusaoetapa($value['id']);


					if(isset($conclusao[0]['inicio'])){
						echo '<td>'.date('d/m/Y H:i:s',strtotime($conclusao[0]['inicio'])).'</td>';
					}
					else {
						echo '<td>---</td>';
					}
					if(isset($conclusao[0]['dia'])){
						echo '<td>'.date('d/m/Y H:i:s',strtotime($conclusao[0]['dia'])).'</td>';
					}else {
						echo '<td>---</td>';
					}
					
					//echo $this->horastrabalhadas($value['inicio'], $value['fim']);

					if ($value['status'] == 'aberto') {
						echo '<td><span class="label label-default">Aberto</span></td>';
					}
					if ($value['status'] == 'em andamento') {
						echo '<td><span class="label label-warning">Em andamento</span></td>';
						$total_h_t = $this->horastrabalhadas($conclusao[0]['inicio'], date('Y-m-d H:i:s'));
					}
					if ($value['status'] == 'concluido') {
						echo '<td><span class="label label-success">Concluido</span></td>';

						//$info_log = $this->conclusaoetapa($value['id']);
						//$data_conclusao = $info_log[0]['dia'];
						$total_h_t = $this->horastrabalhadas(   $conclusao[0]['inicio']   , $conclusao[0]['dia']);
					}
					
					echo '<td>'.$total_h_t.'</td>';

					if($total_h_t != '---' && (double)$this->kilometragem > 0) {
						$kmh = number_format((double)$this->kilometragem / $total_h_t,2);
					} else {
						$kmh = '---';
					}
					echo '<td>'.$kmh.'</td>';

					echo '</tr>';
				}
			} 
			
		 ?>

	</table>

</div>



