<ol class="breadcrumb">
  <li  ><span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span> Projetos</li>
</ol>

<style>
	.flash1_msg {
		margin-bottom: 20px;
	}

</style>
<?php if (count($this->messages)) : ?>
    <br>
    <?php foreach ($this->messages as $message) : ?>
        	<?php echo $message; ?>
    <?php endforeach; ?>
<?php endif; ?>


<p>
<a href="<?php echo $this->baseUrl('/admin/projetos/add'); ?>"><button type="button" class="btn btn-success"><span class="glyphicon glyphicon-plus" ></span>  Adicionar</button></a></p>
<br>

<style>
	.filtrosp {
		margin-bottom: 10px;
		float: right;
	}
</style>
<div class="filtrosp">
	<form class="form-inline" method="post" action="<?php echo $this->baseUrl("admin/projetos"); ?>">
	  <div class="form-group">
	  	<select class="form-control" name="empresas">
	  	<option value="0" label="Todos os clientes" <?php if($this->valor == 0) {echo 'selected';} ?>>Todos os clientes</option>
		<?php 
		foreach ($this->clientes as $key => $value) {
			?>
			<option value="<?php echo $key ?>" label="<?php echo $value ?>" <?php if($this->valor == $key) {echo 'selected'; } ?>><?php echo $value ?></option>
		  
			<?php
		}
		 ?>

		</select>
	  	
	    <input type="text" class="form-control" name="date_de" id="date_de" placeholder="de" value="<?php echo $this->data_de; ?>">
	  </div>
	  <div class="form-group">
	    <input type="text" class="form-control" name="date_ate" id="date_ate" placeholder="até" value="<?php echo $this->data_ate; ?>">
	  </div>
		<button type="submit" class="btn btn-default">Procurar</button>
		<a href="<?php echo $this->baseUrl("admin/projetos/index/filtro/atrasado"); ?>"><button type="button" name="atrasados" class="btn btn-danger btn-xs">Atrasados</button></a>
		<a href="<?php echo $this->baseUrl("admin/projetos/index/filtro/andamento"); ?>"><button type="button" name="em andamento" class="btn btn-warning btn-xs">Em andamento</button></a>
		<a href="<?php echo $this->baseUrl("admin/projetos/index/filtro/concluido"); ?>"><button type="button" name="concluidos" class="btn btn-success btn-xs">Concluídos</button></a>
	</form>
</div>


<script>
	$(document).ready(function () {
	    /* assuming that text input datePicker would have id='datePicker' */
	    $( "#date_de" ).datepicker({ dateFormat: 'dd/mm/yy' });
	    $( "#date_ate" ).datepicker({ dateFormat: 'dd/mm/yy' });

	});
</script>



<table class="table table-hover">

<tr>
	<td><strong>Nome</strong></td>
	<td><strong>Data Inicial</strong></td>
	<td><strong>Data Final</strong></td>
	<td><strong>Concluído</strong></td>
	<td></td>
	<td></td>
	<td><strong>Dias restantes</strong></td>
</tr>

<?php
 foreach ($this->registros as $projetos):
$mostrar_conteudo = 1;


if($this->filtroParam == "concluido"  &&  $this->projetos($projetos['id']) != 100)  {
	$mostrar_conteudo = 0;
}


if($this->filtroParam == "andamento"  &&  $this->projetos($projetos['id']) == 100 ) {
	$mostrar_conteudo = 0;
}


if($this->filtroParam == 'atrasado' &&  $this->projetos($projetos['id']) == 100){
 	$mostrar_conteudo = 0;
}



if($mostrar_conteudo == 1) {
?>
	<tr>
		<td>  <a href="<?php echo $this->baseUrl("admin/projetos/etapas/id/" . $projetos['id']); ?>"> <?php echo '<strong>'.$projetos['nome_cliente'] . '</strong> - ' . $projetos['nome']; ?> </a></td>
		<td><?php echo date('d/m/Y',strtotime($projetos['inicio'])); ?></td>
		<td><?php echo date('d/m/Y',strtotime($projetos['fim'])); ?></td>

		<td>
			
			<div class="progress">
			  <div class="progress-bar " role="progressbar" aria-valuenow="<?php echo $this->projetos($projetos['id']); ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $this->projetos($projetos['id']); ?>%;">
			    <?php echo $this->projetos($projetos['id']); ?>%
			  </div>
			</div>

		</td>

		<td> <a href="<?php echo $this->baseUrl("admin/projetos/etapas/id/" . $projetos['id']); ?>"><button class="btn btn-info btn-xs">  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Adicionar Etapas</button> </a>
		
    <a href="<?php echo $this->baseUrl("admin/projetos/deletarprojeto/id/" . $projetos['id']); ?>" onclick="return confirm('Você quer excluir esse projeto?')">
    <button class="btn btn-danger btn-xs">  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Excluir</button></a>
		</td>
		<td>
			<?php 

			$data_atual =  strtotime(date("m/d/Y")); 
			$data_projeto_entrega = strtotime(   $projetos['fim']   );

			if($this->projetos($projetos['id']) < 100) {
				echo ' <span class="label label-warning">Em andamento</span> ';
			}

			if(  ($data_atual > $data_projeto_entrega) && ($this->projetos($projetos['id']) < 100)  ) {
				echo ' <span class="label label-danger">Atrasado</span> ';
			}

			if ($this->projetos($projetos['id']) == 100)  {
				echo ' <span class="label label-success">Concluído</span> ';
			}
			 ?>
			
		</td>
		<td><?php 
			$data1 = new DateTime( date('Y/m/d',strtotime($projetos['fim'])) );
	        $data2 = new DateTime(  date("Y/m/d")	 );
	        $intervalo = $data1->diff( $data2 );
	        echo $intervalo->d;
	        if(  ($data_atual > $data_projeto_entrega) && ($this->projetos($projetos['id']) < 100)  ) {
				echo ' <span class="label label-danger">Atrasado</span> ';
			}

		 ?></td>
	</tr>

<?php

}
 endforeach;
 ?>


</table>




<!-- 
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">Todos</a></li>
  <li role="presentation"><a href="#">Concluídos</a></li>
  <li role="presentation" class="disabled"><a href="#">Em andamento</a></li>


</ul> -->