 <script src="<?php echo $this->baseUrl("js/jquery.mask.js"); ?>"></script>

<ol class="breadcrumb">
  <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Funcionários</li>
  <li class="active"><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>  Cadastrar</li>
</ol>



<style>
	.func_cadastro {
		width: 300px;
		float: left;
		margin-left: 66px;
		margin-bottom: 200px;
	}
	
	.errors {
		list-style:none;
		color: #FF0000;
		padding: 0;
	}

	.flash1_msg {
		margin-bottom: 20px;
	}
</style>
<div class="func_cadastro">
<div class="flash1_msg" style="color:green">
<?php if (count($this->messages)) : ?>
    <?php foreach ($this->messages as $message) : ?>
    <div id="field_name">
        <?php echo $message; ?>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
</div>

<?php
echo $this->formularioCadastro;
?>
</div>


<script>
	$(document).ready(function () {
	    /* assuming that text input datePicker would have id='datePicker' */
	    $( "#admissao" ).datepicker({ dateFormat: 'dd/mm/yy' });
	     $('#salario').mask('000.000.000.000.000,00', {reverse: true});
	});
</script>
