<ol class="breadcrumb">
  <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Funcionários</li>
  <li class="active"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>  Visualizar</li>
</ol>


<p>
<a href="<?php echo $this->baseUrl("admin/funcionarios/cadastrar"); ?>">
<button type="button" class="btn btn-default">Adicionar</button>
</a>
</p>


<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Procurar funcionários...">
      <span class="input-group-btn">
        <button class="btn btn-success" type="button">Buscar</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->


<?php if (count($this->messages)) : ?>
    <br>
    <?php foreach ($this->messages as $message) : ?>
        <div class="alert alert-success" role="alert"><?php echo $this->escape($message); ?></div>
    <?php endforeach; ?>
<?php endif; ?>

<br>

<table class="table table-hover">

<tr>
	<td><strong>Nome</strong></td>
	<td><strong>E-mail</strong></td>
	<td><strong>Rg</strong></td>
	<td><strong>Data de nascimento</strong></td>
	<td><strong>Data de cadastro</strong></td>
	<td></td>
</tr>

<?php
 foreach ($this->registros as $funcionarios):
?>
	<tr>
		<td> <?php echo $funcionarios['nome']; ?> </td>
		<td><?php echo $funcionarios['email']; ?></td>
		<td><?php echo $funcionarios['rg']; ?></td>
		<td><?php echo $funcionarios['data_nascimento']; ?></td>
		<td><?php echo date('d/m/Y H:m:s', strtotime($funcionarios['data_cadastro'])); ?></td>
		<td> <a href="<?php echo $this->baseUrl("admin/funcionarios/editar/id/" . $funcionarios['id_user']); ?>"><button class="btn btn-info btn-xs">  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar</button> </a>
		
    <a href="<?php echo $this->baseUrl("admin/funcionarios/delete/id/" . $funcionarios['id_user']); ?>" onclick="return confirm('Você quer excluir esse funcionario?')">
    <button class="btn btn-danger btn-xs">  <span class="glyphicon glyphicon-trash" aria-hidden="true" ></span> Excluir</button></a>
		</td>
	</tr>

<?php
 endforeach;
 ?>

</table>

<?php
    echo $this->paginationControl(
                $this->registros,
                'Sliding',
                'paginator.phtml'
            );

?>