<ol class="breadcrumb">
  <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Funcionários</li>
  <li class="active"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>  Visualizar</li>
</ol>


<p>
<a href="<?php echo $this->baseUrl("admin/funcionarios/cadastrar"); ?>">
<button type="button" class="btn btn-default">Adicionar</button>
</a>
</p>


<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Procurar funcionários...">
      <span class="input-group-btn">
        <button class="btn btn-success" type="button">Buscar</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->


<?php if (count($this->messages)) : ?>
    <br>
    <?php foreach ($this->messages as $message) : ?>
        <?php echo $message; ?>
    <?php endforeach; ?>
<?php endif; ?>

<br>

<table class="table table-hover" id="tabela_usuarios">

<tr>
  <td><strong></strong></td>
	<td><strong>Nome</strong></td>
	<td><strong>E-mail</strong></td>
	<td><strong>Tempo serviço</strong></td>
	<td><strong>Data de admissão</strong></td>

	<td></td>
</tr>

<?php
 foreach ($this->registros as $funcionarios):
?>
	<tr>
    <td> <input type="checkbox" name="vehicle" value="Bike" class="ck_user"> </td>
		<td> <?php echo $funcionarios['nome']; ?> </td>
		<td><?php echo $funcionarios['email']; ?></td>
		<td><?php echo $this->funcoes->diff2(date("d/m/Y", strtotime($funcionarios['admissao']) ), date("d/m/Y") ) . ' dias'; ?></td>
		<td><?php echo $this->funcoes->volta_data_ao_normal($funcionarios['admissao']); ?></td>
		<td> <a href="<?php echo $this->baseUrl("admin/funcionarios/editar/id/" . $funcionarios['id_user']); ?>"><button class="btn btn-info btn-xs">  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar</button> </a>
		
    <a href="<?php echo $this->baseUrl("admin/funcionarios/delete/id/" . $funcionarios['id_user']); ?>" onclick="return confirm('Você quer excluir esse funcionario?')">
    <button class="btn btn-danger btn-xs">  <span class="glyphicon glyphicon-trash" aria-hidden="true" ></span> Excluir</button></a>
		</td>
	</tr>

<?php
 endforeach;
 ?>

</table>

<script type="text/javascript">

  //Procura usuários que estão selecionados, para cumprir com
  //uma determinada ação
  function procura_usuarios() {
    var anchor = null;
    var container;
    var items;

    container = document.getElementById('tabela_usuarios');
    items = container.getElementsByTagName('input');

    for (var j = 0; j < items.length; j++) {
        var x = items[j].checked;
        
        //if (items[j].href === 'http://www.msn.com') {
        //   anchor = items[j];
        //    break;
        //}
    }
  };
  
  procura_usuarios();
</script>

<?php
    echo $this->paginationControl(
                $this->registros,
                'Sliding',
                'paginator.phtml'
            );

?>