<ol class="breadcrumb">
  <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Funcionários</li>
  <li class="active"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>  Visualizar</li>
</ol>


<p>
  <a href="<?php echo $this->baseUrl("admin/funcionarios/cadastrar"); ?>">
    <button type="button" class="btn btn-default">Adicionar</button>
  </a>
</p>


<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control find_user" placeholder="Procurar funcionários...">
      <span class="input-group-btn">
        <button class="btn btn-success" type="button" onclick="buscar_usuarios()" >Buscar</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->


<?php if (count($this->messages)) : ?>
    <br>
    <?php foreach ($this->messages as $message) : ?>
        <?php echo $message; ?>
    <?php endforeach; ?>
<?php endif; ?>

<br>


<!-- Adaptação1 - Início -->
<style>
  .selecionados {
    background-color:#F5F5F5 ;
    border: 1px dotted #c2c2c2;
    border-radius: 10px;
    padding:10px;
  }

  .resultado {
    color: #ff0000;
    padding:10px;
  }
</style>
<div class="selecionados">
  <b>Selecionados</b> 
  <button onclick="selecionarTodos(this)">Todos</button>
  <button onclick="procura_usuarios()">Excluir</button>
</div>
<!-- Adaptação1 - Fim -->



<br>

<table class="table table-hover" id="tabela_usuarios">

<tr>
  <td><strong></strong></td>
	<td><strong>Nome</strong></td>
	<td><strong>E-mail</strong></td>
	<td><strong>Tempo serviço</strong></td>
	<td><strong>Data de admissão</strong></td>

	<td></td>
</tr>

<?php
 foreach ($this->registros as $funcionarios):
?>
	<tr class="ck_user<?php echo $funcionarios['id_user'] ?>">
    <td > <input class="checkbox<?php echo $funcionarios['id_user'] ?>" type="checkbox" name="vehicle" value="<?php echo $funcionarios['id_user'] ?>" > </td>
		<td> <a href="<?php echo $this->baseUrl("admin/funcionarios/editar/id/" . $funcionarios['id_user']); ?>"><?php echo $funcionarios['nome']; ?> </a> </td>
		<td><?php echo $funcionarios['email']; ?></td>
		<td><?php echo $this->funcoes->diff2(date("d/m/Y", strtotime($funcionarios['admissao']) ), date("d/m/Y") ) . ' dias'; ?></td>
		<td><?php echo $this->funcoes->volta_data_ao_normal($funcionarios['admissao']); ?></td>
		<td> <a href="<?php echo $this->baseUrl("admin/funcionarios/editar/id/" . $funcionarios['id_user']); ?>"><button class="btn btn-info btn-xs">  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar</button> </a>

    <a href="<?php echo $this->baseUrl("admin/funcionarios/delete/id/" . $funcionarios['id_user']); ?>" onclick="return confirm('Você quer excluir esse funcionario?')">
    <button class="btn btn-danger btn-xs">  <span class="glyphicon glyphicon-trash" aria-hidden="true" ></span> Excluir</button></a>
		</td>
	</tr>

<?php
 endforeach;
 ?>

</table>



<script type="text/javascript">
  function buscar_usuarios() {
    var user_input;
    user_input = document.getElementsByClassName("find_user")[0].value.trim();
    if(user_input.length != 0) {
      window.location.replace(BASEURL + "admin/funcionarios/visualizar/procurar/" + user_input);
    } else {
      window.location.replace(BASEURL + "admin/funcionarios/visualizar");
    }
  }


  var tabelaUser = "tabela_usuarios";

  //marca todos os checkbox dos usuários
  function selecionarTodos(obj) {
    var valor;

    container = document.getElementById(tabelaUser);
    items = container.getElementsByTagName('input');
    label = obj.innerHTML; // Valor presente no botão. Poder ser todos, ou nenhum
    if (label == "Todos") {
      obj.innerHTML = "Nenhum";
      valor = true;
    } else {
      obj.innerHTML = "Todos";
      valor = false;
    }

    for (var j = 0; j < items.length; j++) {
        //Se o elemento está visível na página
        if(  $(items[j]).is(":visible") == true )
        {  
             items[j].checked = valor;
        }
    }
  }

  //Procura usuários que estão selecionados, para cumprir com
  //uma determinada ação
  function procura_usuarios() {
    if (!confirm('Deseja realmente excluir os funcionários?')) {
        return false;
    }

    //var anchor = null;
    var container;
    var items;
    var resultado;
    resultado = '';

    container = document.getElementById(tabelaUser);
    items = container.getElementsByTagName('input');

    for (var j = 0; j < items.length; j++) {
        if(items[j].checked == true) {
          idCliente = items[j].value; // return string
          $.ajax({
            type: 'POST',
            url: BASEURL + 'admin/funcionarios/ajaxexcluir', //Adaptação1 <= Especificar a url
            data: { id : idCliente },
            async: false,
            success: function(response) {
              resultado = resultado + response;
            }

          });

          //Verifica se a classe 'resultado' existe
          if (!$(".resultado")[0]){
              $(".selecionados").after("<div class='resultado'></div>")
          }

          $('.resultado').html(resultado);
          $(".ck_user" + idCliente).hide();
          $(".checkbox" + idCliente).prop("checked", false);
        }
    }
    return false
  };

</script>

<?php
    echo $this->paginationControl (
                $this->registros,
                'Sliding',
                'paginator.phtml'
          );

?>