<a href="<?php echo $this->baseUrl('user/grupos/visualizar'); ?>"><button type="button" class="btn btn-success btn-xs"> <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span> Voltar</button></a>



<style>
	.filtrosp {
		margin-bottom: 20px;
		float: right;
	}
</style>

<div class="filtrosp">
	<form class="form-inline" method="post" action="<?php echo $this->baseUrl("user/index/index/idgrupo/" . $this->idGrupo); ?>">
	  <div class="form-group">
	  	
	    <input type="text" class="form-control" name="date_de" id="date_de" placeholder="de" value="<?php echo $this->data_de; ?>">
	  </div>
	  <div class="form-group">
	    <input type="text" class="form-control" name="date_ate" id="date_ate" placeholder="até" value="<?php echo $this->data_ate; ?>">
	  </div>
		<button type="submit" class="btn btn-default">Procurar</button>
		<a href="<?php echo $this->baseUrl("user/index/index/filtro/atrasado/idgrupo/". $this->idGrupo); ?>"><button type="button" name="atrasados" class="btn btn-danger btn-xs">Atrasados</button></a>
		<a href="<?php echo $this->baseUrl("user/index/index/filtro/andamento/idgrupo/". $this->idGrupo); ?>"><button type="button" name="em andamento" class="btn btn-warning btn-xs">Em andamento</button></a>
		<a href="<?php echo $this->baseUrl("user/index/index/filtro/concluido/idgrupo/". $this->idGrupo); ?>"><button type="button" name="concluidos" class="btn btn-success btn-xs">Concluídos</button></a>
	</form>
</div>
<br>



<script>
	$(document).ready(function () {
	    /* assuming that text input datePicker would have id='datePicker' */
	    $( "#date_de" ).datepicker({ dateFormat: 'dd/mm/yy' });
	    $( "#date_ate" ).datepicker({ dateFormat: 'dd/mm/yy' });

	});
</script>

<style>
	.table {
		width: 666px;
	}
</style>

<table class="table table-hover">

<tr>
	<td><strong>Nome</strong></td>
	<td><strong>Data Inicial</strong></td>
	<td><strong>Data Final</strong></td>
	<td><strong>Concluído</strong></td>
	<td></td>
	<td><strong>Dias restantes</strong></td>
</tr>

<?php
 foreach ($this->registros as $projetos):
$mostrar_conteudo = 1;


if($this->filtroParam == "concluido"  &&  $this->projetos($projetos['id']) != 100)  {
	$mostrar_conteudo = 0;
}


if($this->filtroParam == "andamento"  &&  $this->projetos($projetos['id']) == 100 ) {
	$mostrar_conteudo = 0;
}


if($this->filtroParam == 'atrasado' &&  $this->projetos($projetos['id']) == 100){
 	$mostrar_conteudo = 0;
}

if($mostrar_conteudo == 1) {

$minhasTarefas = $this->minhastarefas($projetos['id'], $this->id_usuario);
$tarefaspendentes = $this->tarefaspendentes($projetos['id'], $this->id_usuario);
$tarefaspendentes2 = $this->tarefaspendentes2($projetos['id'], $this->id_usuario);
$sedisponivel = $this->verificatarefasaberto($projetos['id']);


?>
	<tr>
		<td><a href="<?php echo $this->baseUrl("user/projetos/visualizar/id/" . $projetos['id']."/idgrupo/" . $this->idGrupo); ?>"><?php echo $projetos['nome']; ?></a>  <?php if ($tarefaspendentes) { echo '<small><i><font color="red">pendente</font></i></small>'; } else { if($tarefaspendentes2) { echo '<small><i><font color="red">pendente</font></i></small>'; } } 

		if($sedisponivel) {
			echo ' <small><font color="#c2c2c2">disponível</font></small>';
		}

		?>  </td>
		<td><?php echo date('d/m/Y',strtotime($projetos['inicio']));  ?></td>
		<td><?php echo date('d/m/Y',strtotime($projetos['fim']));  ?></td>

		<td>
			
			<div class="progress">
			  <div class="progress-bar " role="progressbar" aria-valuenow="<?php echo $this->projetos($projetos['id']); ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $this->projetos($projetos['id']); ?>%;">
			    <?php echo $this->projetos($projetos['id']);  ?>%
			  </div>
			</div>

		</td>

		<td>
			<?php 

			$data_atual =  strtotime(date("m/d/Y")); 
			$data_projeto_entrega = strtotime(   $projetos['fim']   );

			if($this->projetos($projetos['id']) < 100) {
				echo ' <span class="label label-warning">Em andamento</span> ';
			}

			if(  ($data_atual > $data_projeto_entrega) && ($this->projetos($projetos['id']) < 100)  ) {
				echo ' <span class="label label-danger">Atrasado</span> ';
			}

			if ($this->projetos($projetos['id']) == 100)  {
				echo ' <span class="label label-success">Concluído</span> ';
			}
			 ?>
			
		</td>
		<td><?php 
			$data1 = new DateTime( date('Y/m/d',strtotime($projetos['fim'])) );
	        $data2 = new DateTime(  date("Y/m/d")	 );
	        $intervalo = $data1->diff( $data2 );
	        echo $intervalo->y . ' ano(s) ' . $intervalo->m . ' mes(es) ' . $intervalo->d . ' dia(s)';
	        if(  ($data_atual > $data_projeto_entrega) && ($this->projetos($projetos['id']) < 100)  ) {
				echo ' <span class="label label-danger">Atrasado</span> ';
			}

		 ?></td>
	</tr>

<?php

}
 endforeach;
 ?>


</table>
