<a href="<?php echo $this->baseUrl('/user'); ?>"><button type="button" class="btn btn-success btn-xs"> <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span> Voltar</button></a>
<br>
<br>
<style>
	
	.minhas_tarefas {
		width: 444px;
		float: left;
	}

	.todas-etapas{
		float: left;
		margin-left: 122px;
	}
</style>
<h3>Projeto CPFL</h3>
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="45.5" aria-valuemin="0" aria-valuemax="100" style="width: 45.5%;">
    45.5%
  </div>
</div>



<div class="minhas_tarefas">
	<h3>Minhas tarefas</h3>
	<table class="table table-hover">
		<tr>
			<td><strong>Etapa</strong></td>
			<td><strong>Data início</strong></td>
			<td><strong>Data final</strong></td>
			<td><strong>Dias restantes</strong></td>
			<td><strong>Status</strong></td>
		</tr>
		<tr>
			<td><a href="#">Desenhar mapa</a></td>
			<td>03/02/2015</td>
			<td>03/03/2015</td>
			<td>30</td>
			<td><span class="label label-warning">Em andamento</span></td>
		</tr>
	</table>
</div>

<div class="todas-etapas">
	
	<h3>Todas as etapas do projeto</h3>
	<table class="table table-hover">
		<tr>
			<td><strong>Etapa</strong></td>
			<td><strong>Usuário</strong></td>
			<td><strong>Status</strong></td>
			<td></td>
		</tr>
		<tr>
			<td>Converter mapa</td>
			<td>#</td>
			<td><span class="label label-default">Aberto</span></td>
			<td><a href="#"><span class="glyphicon glyphicon-plus"></span></a></td>
		</tr>
		<tr>
			<td>Editar mapa</td>
			<td>#</td>
			<td><span class="label label-default">Aberto</span></td>
			<td><a href="#"><span class="glyphicon glyphicon-plus"></span></a></td>
		</tr>
		<tr>
			<td>Desenhar</td>
			<td>#</td>
			<td><span class="label label-default">Aberto</span></td>
			<td><a href="#"><span class="glyphicon glyphicon-plus"></span></a></td>
		</tr>
		<tr>
			<td>Controle de Qualidade</td>
			<td>Debora Duarte Moreira</td>
			<td><span class="label label-warning">Em andamento</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Extrair blocos</td>
			<td>Fernanda Barbi</td>
			<td><span class="label label-warning">Em andamento</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Converter mapa</td>
			<td>Renan Peliçari</td>
			<td><span class="label label-success">Concluído</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Converter mapa</td>
			<td>#</td>
			<td><span class="label label-default">Aberto</span></td>
			<td><a href="#"><span class="glyphicon glyphicon-plus"></span></a></td>
		</tr>
		<tr>
			<td>Converter mapa</td>
			<td>#</td>
			<td><span class="label label-default">Aberto</span></td>
			<td><a href="#"><span class="glyphicon glyphicon-plus"></span></a></td>
		</tr>
		<tr>
			<td>Converter mapa</td>
			<td>#</td>
			<td><span class="label label-default">Aberto</span></td>
			<td><a href="#"><span class="glyphicon glyphicon-plus"></span></a></td>
		</tr>
	</table>
</div>
